import { useEffect, useMemo, useState } from 'react'
import { Search, Upload, X } from 'lucide-react'
import { userService } from '../../services/userService'
import UserAvatar from '../users/UserAvatar'

export default function CreateGroupModal({ onClose, onCreate }) {
    const [friends, setFriends] = useState([]); const [selected, setSelected] = useState([]); const [name, setName] = useState(''); const [query, setQuery] = useState(''); const [avatar, setAvatar] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
    useEffect(() => { userService.getFriends().then(setFriends).catch(() => setError('Unable to load friends.')) }, [])
    const visible = useMemo(() => friends.filter(friend => friend.username.toLowerCase().includes(query.toLowerCase())), [friends, query])
    const toggle = id => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
    const submit = async event => { event.preventDefault(); if (!name.trim() || !selected.length) return setError('Enter a group name and select at least one friend.'); setBusy(true); setError(''); try { await onCreate({ name: name.trim(), memberIds: selected, avatar }); onClose() } catch (err) { setError(err.response?.data?.message || err.message || 'Unable to create group.') } finally { setBusy(false) } }
    return <div className="group-modal-layer" onClick={() => !busy && onClose()}><form className="group-modal" onSubmit={submit} onClick={event => event.stopPropagation()}><div className="group-modal-heading"><div><h2>Create group</h2><p>Choose friends to start a conversation.</p></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><label className="field"><span>Group name</span><input value={name} onChange={event => setName(event.target.value)} maxLength="80" required autoFocus /></label><label className="group-upload"><Upload size={16}/><span>{avatar?.name || 'Add group picture (optional)'}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={event => setAvatar(event.target.files?.[0] || null)} /></label><label className="group-search"><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search friends" /></label><div className="group-counter">{selected.length} selected</div><div className="group-friends">{visible.map(friend => <label key={friend.id} className="group-friend"><input type="checkbox" checked={selected.includes(friend.id)} onChange={() => toggle(friend.id)} /><UserAvatar user={friend} alt="" /><span>{friend.username}</span></label>)}</div>{error && <p className="inline-error">{error}</p>}<div className="group-modal-actions"><button type="button" className="ghost-button" onClick={onClose} disabled={busy}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? 'Creating…' : 'Create group'}</button></div></form></div>
}
